import { shuffle } from 'lodash'

export const PROMPTS_LIST = [
  'Someone gets left behind',
  'Someone starts drinking before midday',
  "Someone doesn't make it down in time before breakfast",
  'Someone thinks they have lost their passport',
  'Josh is lying on the floor',
  'Benny is a dad',
  'Group study session',
  'Someone passes out',
  'Someone hooks up with a Spaniard',
  'Ellie has a breakdown',
  'Someone looses their key',
  'Piotr makes an inappropriate joke',
  "Daria pulls Josh's arm",
  'Josh gets scared',
  'Kacper starts talking about philosophy',
  'Someone breaks something in their room',
  'Someone tries to speak Spanish and fails',
  'Someone gets injured',
  'Someone gets pickpocketed',
  'Someone throws up in the bus/bar',
  'Someone swims in the sea',
  'A couple starts dancing on the street',
  'Greg gets approached by a woman in a bar',
  'Serena gets a sugar daddy',
  'Serena gets asked on a (Tinder) date',
  'Serena gets kidnapped',
  'CIRCLEEEEE!',
  'Benny puts his eye mask on',
  'Emily goes missing',
  'Serens says slay and does the hand thing',
  'Piotr, Greg and Kacper all start speaking Polish in a group setting',
  'Someone snores during the night',
  'Someone sleepwalks/sleep-talks',
  'Someone starts a fight',
  'Daria says "excuse youuuuuuuu"',
  'Claire complains about engineering',
  'Josh says "Damn it" to one or all of Daria, Claire, Emily and Alys',
  'Josh gets asked about bingo',
  'Josh pays for a meal',
  'Emily loses her phone',
  '17 simultaneous be-reals',
  'Someone is sick off of the two-euro Sangria',
  'Josh starts speaking German',
]

export const PROMPTS = (): string[] => shuffle(PROMPTS_LIST).slice(0, 25)
